# Enable OS
os: windows

# Enable Lang
language: cpp

# Enable Compilers
compiler:
  - gcc
  - clang

# Pre-Install
before_install:
  - echo $PATH
  - choco install conan
  - $env:ChocolateyInstall = Convert-Path "$((Get-Command choco).path)\..\.."
  - Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"

# Install
install:
  - refreshenv
  - echo $PATH
  - mkdir conan
  - cd conan
  - conan install ..

# Setup Build
before_script:
  - cd ..
  - mkdir build
  - cd build
  - cmake ..
  
# Build and Test
script:
  - make && make test
