# Enable C++
language: cpp

# Enable Compilers
compiler:
  - gcc
  - clang
  
# Setup Build
before_script:
  - mkdir conan
  - cd conan
  - conan install ..
  - cd ..
  - mkdir build
  - cd build
  - cmake ..
  
# Build and Test
script: make && make test
