# Enable OS
os: windows

# Enable Lang
language: cpp

# Enable Compilers
compiler:
  - MSVC
  - gcc
  - clang

# Pre-Install
before_install:

# Install
install:
  - echo $PATH
  - choco upgrade chocolatey
  - choco install conan
  - export PATH="/c/Program Files/Conan/conan:$PATH"
  - echo $PATH
  

# Setup Build
before_script:
  - conan inspect sfml/2.5.1@bincrafters/stable
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

# Build and Test
script:
  - mkdir conan && cd conan
  - conan install -b missing ..
  - cd ..
  - mkdir build && cd build
  - cmake ..
  - make && make test
