# Enable OS
os: windows

# Enable Lang
language: cpp

# Enable Compilers
compiler:
  - MSVC
  - gcc
  - clang

# Pre-Install
before_install:

# Install
install:
  - echo $PATH
  - choco upgrade chocolatey
  - choco install conan
  - echo $PATH

# Setup Build
before_script:
  - mkdir conan
  - cd conan
  - conan install ..
  - cd ..
  - mkdir build
  - cd build
  - cmake ..
  
# Build and Test
script:
  - make && make test
