# Enable OS
os: windows

# Enable Lang
language: cpp

# Enable Compilers
compiler:
  - gcc
  - clang

# Pre-Install
before_install:
  - echo $PATH
  - choco install conan
  
# Setup Build
script:
  - mkdir conan
  - cd conan
  - conan install ..
  - cd ..
  - mkdir build
  - cd build
  - cmake ..
  - make && make test
