# Enable OS
os: windows

# Enable Lang
language: cpp

# Enable Compilers
compiler:
  - msvc

# Pre-Install
before_install:

# Install
install:
  - echo $PATH
  - choco upgrade chocolatey
  - choco install conan
  - export PATH="/c/Program Files/Conan/conan:$PATH"
  - echo $PATH

# Setup Build
before_script:
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan inspect sfml/2.5.1@bincrafters/stable
  
# Build and Test
script:
  - mkdir conan && cd conan
  - conan install -s compiler="Visual Studio" -s compiler.version=15 -s arch=x86_64 -s build_type=Release -b missing ..
  - cd ..
  - mkdir build && cd build
  - cmake -G "Visual Studio 15 2017" ..
  - cmake --build .
